### ISSUE TITLE
how to host in vps

### ISSUE THREAD

**Issue by jerry-619** [Andndre/chatgpt-whatsapp#36]
i'm not able to host bot in ubuntu vps it gives some error can you help me

**Comment by heyfolk** [comment]
i am getting this error

file:///home/runner/chatgpt-whatsapp/node_modules/chatgpt/build/index.js:174
      throw new Error("Invalid environment; fetch is not defined");
            ^

Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///home/runner/chatgpt-whatsapp/node_modules/chatgpt/build/index.js:174:13)
    at file:///home/runner/chatgpt-whatsapp/dist/index.js:7:20
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
exit status 1

**Comment by Andndre** [comment]
As mentioned in [this issue](https://github.com/transitive-bullshit/chatgpt-api/issues/572#issuecomment-1560807954), you need to use node>=18 so fetch is available.

or maybe you can try to install [this package](https://github.com/developit/unfetch#usage-as-a-polyfill)?
